services:
  ollama:
    image: dustynv/ollama:r36.4-cu129-24.04
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_NUM_GPU=1
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11437:11434"
    entrypoint: ["/bin/bash","-lc"]
    command: ["ollama serve"]
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 60
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  rag-agent:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.10-slim
        
        WORKDIR /app
        
        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            curl \
            && rm -rf /var/lib/apt/lists/*
        
        # Install Python packages
        RUN pip install --no-cache-dir \
            flask \
            langchain==0.1.0 \
            langchain-community \
            qdrant-client \
            requests \
            beautifulsoup4
        
        # Create directories
        RUN mkdir -p /app/uploads
        
        COPY rag-agent.py /app/
        
        CMD ["python", "rag-agent.py"]
    
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_started
    
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - LLM_MODEL=qwen2.5:3b
      - EMBED_MODEL=nomic-embed-text
    
    volumes:
      - ./uploads:/app/uploads
    
    ports:
      - "8080:7861"
    
    restart: unless-stopped
